#include "HarlowGameMode.h"

AHarlowGameMode::AHarlowGameMode()
{
	// http://api.unrealengine.com/INT/API/Runtime/Engine/GameFramework/AGameModeBase/index.html
	// DefaultPawnClass = ...

	// GameSessionClass = ...

	// GameStateClass = ...

	// PlayerControllerClass = ...
	
	// PlayerStateClass = ...

	// SpectatorClass = ...
}